version: '3.8'
services:
  db:
    image: postgres:alpine
    hostname: secureDb
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: securityBlogDB
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://secureDb:5432/securityBlogDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/code
volumes:
  data:
