spring:
  datasource:
    url: jdbc:postgresql://secureDb:5432/securityBlogDB
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secretKey: 556A586E327235753878214125442A472D4B6150645367566B59703373367639
      expiration: 86400000
  version: v1

#  60000
#  604800000