    name: Build and deploy Spring Security app

    on: [push]

    jobs:
      build-deploy:
        name: Build and Deploy SpringBoot Application
        runs-on: ubuntu-latest

        services:
          postgres:
            image: postgres:alpine
            env:
              POSTGRES_USERNAME: postgres
              POSTGRES_PASSWORD: password
              POSTGRES_DB: securityBlogDB

            options:
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
           

        steps:

          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup JDK 17
            uses: actions/setup-java@v3
            with:
              distribution: 'corretto'
              java-version: 17

          - name: unit Tests
            run: mvn -B test --file pom.xml

          - name: Build application
            run: |
              mvn clean
              mvn -B package --file pom.xml





